from sqlalchemy.orm import Session
from database import SessionLocal, Base, engine
from models import Product

# -------------------------------
# Step 1: Create tables
# -------------------------------
# This will create the 'eyewear_products' table in your DB if it doesn't exist
Base.metadata.create_all(bind=engine)

# -------------------------------
# Step 2: Full Data List (Fixed for Python)
# -------------------------------
products_data = [
    {
        "name": "Ray-Ban Erika Classic",
        "brand": "Ray-Ban",
        "category": ["sunglasses"],
        "gender": ["female"],
        "description": "The Erika is a staple of modern style, featuring a gummy frame finish and thin metal temples.",
        "face_shapes": ["round", "oval", "heart"],
        "frame_shapes": ["round"],
        "frame_materials": ["nylon", "metal"],
        "frame_colors": ["tortoise", "gunmetal"],
        "lens_shapes": ["round"],
        "lens_colors": ["gradient brown"],
        "arm_size_mm": [140, 141, 142, 143, 144, 145],
        "lens_size_mm": [50, 51, 52, 53, 54, 55],
        "bridge_size_mm": [15, 16, 17, 18, 19, 20],
        "pd_mm": [60, 61, 62, 63, 64],
        "supports_power": True,
        "prescription_types": ["single_vision", "progressive"],
        "sph_min": -8.0, "sph_max": 6.0, "cyl_min": -3.0, "cyl_max": 3.0, "axis_min": 1, "axis_max": 180,
        "blue_cut": True, "anti_glare": True,
        "usage": ["leisure", "fashion"],
        "price_usd": 144.48, "power_price_usd": 150.00, "currency": "USD",
        "stock": 15, "rating": 4.8,
        "keywords": ["ray-ban-erika", "chic"], "tone_descriptors": ["vintage"],
        "style_tags": ["retro"], "recommended_for": ["fashion-lovers"],
        "occasion": ["beach-day"], "tags": ["uv400", "lightweight"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/luximages/0RB4171__710_T5_030Afw350fh218.75.png"]
    },
    {
        "name": "Ray-Ban Clubmaster Heritage",
        "brand": "Ray-Ban",
        "category": ["sunglasses"],
        "gender": ["unisex"],
        "description": "Inspired by the 1950s, the Clubmaster is an unmistakable design worn by cultural intellectuals.",
        "face_shapes": ["round", "oval", "heart"],
        "frame_shapes": ["browline"],
        "frame_materials": ["acetate", "metal"],
        "frame_colors": ["tortoise", "gold"],
        "lens_shapes": ["square"],
        "lens_colors": ["green"],
        "arm_size_mm": [138, 139, 140, 141, 142, 143],
        "lens_size_mm": [47, 48, 49, 50, 51, 52],
        "bridge_size_mm": [19, 20, 21, 22, 23, 24],
        "pd_mm": [62, 63, 64, 65],
        "supports_power": True,
        "prescription_types": ["single_vision", "progressive"],
        "sph_min": -10.0, "sph_max": 8.0, "cyl_min": -4.0, "cyl_max": 4.0, "axis_min": 1, "axis_max": 180,
        "blue_cut": True, "anti_glare": True,
        "usage": ["luxury"], "price_usd": 136.91, "power_price_usd": 160.00, "currency": "USD",
        "stock": 8, "rating": 4.9,
        "keywords": ["clubmaster"], "tone_descriptors": ["iconic"],
        "style_tags": ["50s-inspired"], "recommended_for": ["collectors"],
        "occasion": ["business"], "tags": ["classic-g15"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/luximages/0RB3016__W0366_030Afw350fh218.75.png"]
    },
    {
        "name": "Oakley Eye Jacket Sport",
        "brand": "Oakley",
        "category": ["sunglasses"],
        "gender": ["male"],
        "description": "A sport performance icon with a bold oval silhouette, engineered for high-wrap coverage.",
        "face_shapes": ["square", "diamond"],
        "frame_shapes": ["oval"],
        "frame_materials": ["o-matter"],
        "frame_colors": ["silver"],
        "lens_shapes": ["oval"],
        "lens_colors": ["grey"],
        "arm_size_mm": [135, 136, 137, 138, 139, 140],
        "lens_size_mm": [56, 57, 58, 59, 60],
        "bridge_size_mm": [16, 17, 18, 19, 20],
        "pd_mm": [64, 65, 66],
        "supports_power": False,
        "prescription_types": [],
        "sph_min": 0, "sph_max": 0, "cyl_min": 0, "cyl_max": 0, "axis_min": 0, "axis_max": 0,
        "blue_cut": False, "anti_glare": True,
        "usage": ["sport"], "price_usd": 199.52, "power_price_usd": 0.00, "currency": "USD",
        "stock": 2, "rating": 4.7,
        "keywords": ["oakley-redux"], "tone_descriptors": ["bold"],
        "style_tags": ["performance"], "recommended_for": ["athletes"],
        "occasion": ["cycling"], "tags": ["prizm"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/luximages/0OO9438__943805_030Afw350fh218.75.png"]
    },
    {
        "name": "Gucci Signature Square",
        "brand": "Gucci",
        "category": ["sunglasses"],
        "gender": ["female"],
        "description": "Oversized square profile featuring the Interlocking G logo on the temples.",
        "face_shapes": ["round", "oval"],
        "frame_shapes": ["square"],
        "frame_materials": ["acetate"],
        "frame_colors": ["tortoise"],
        "lens_shapes": ["square"],
        "lens_colors": ["gradient brown"],
        "arm_size_mm": [140, 141, 142, 143, 144, 145],
        "lens_size_mm": [52, 53, 54, 55, 56],
        "bridge_size_mm": [17, 18, 19, 20, 21],
        "pd_mm": [60, 61, 62, 63],
        "supports_power": True,
        "prescription_types": ["single_vision"],
        "sph_min": -4.0, "sph_max": 4.0, "cyl_min": -2.0, "cyl_max": 2.0, "axis_min": 1, "axis_max": 180,
        "blue_cut": False, "anti_glare": True,
        "usage": ["luxury"], "price_usd": 185.76, "power_price_usd": 200.00, "currency": "USD",
        "stock": 5, "rating": 5.0,
        "keywords": ["gucci"], "tone_descriptors": ["glamorous"],
        "style_tags": ["luxury"], "recommended_for": ["fashionistas"],
        "occasion": ["events"], "tags": ["gold-logo"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/product_images/Gucci-Sunglasses-GG1338S-003-54fw350fh218.75.jpg"]
    },
    {
        "name": "Ray-Ban Urban Oval",
        "brand": "Ray-Ban",
        "category": ["sunglasses"],
        "gender": ["unisex"],
        "description": "A modern, low-profile oval design with thick temples and a solid bridge.",
        "face_shapes": ["square", "diamond"],
        "frame_shapes": ["oval"],
        "frame_materials": ["propionate"],
        "frame_colors": ["brown"],
        "lens_shapes": ["oval"],
        "lens_colors": ["brown"],
        "arm_size_mm": [142, 143, 144, 145, 146],
        "lens_size_mm": [55, 56, 57, 58, 59],
        "bridge_size_mm": [16, 17, 18, 19, 20],
        "pd_mm": [63, 64, 65],
        "supports_power": True,
        "prescription_types": ["single_vision"],
        "sph_min": -5.0, "sph_max": 4.0, "cyl_min": -2.0, "cyl_max": 2.0, "axis_min": 1, "axis_max": 180,
        "blue_cut": False, "anti_glare": True,
        "usage": ["urban"], "price_usd": 130.90, "power_price_usd": 140.00, "currency": "USD",
        "stock": 3, "rating": 4.5,
        "keywords": ["minimalist"], "tone_descriptors": ["sleek"],
        "style_tags": ["contemporary"], "recommended_for": ["youth"],
        "occasion": ["city-travel"], "tags": ["durable"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/product_images/Ray-Ban-Sunglasses-RB4441D-677973-afw350fh218.75.jpg"]
    },
    {
        "name": "Ray-Ban Aviator Classic",
        "brand": "Ray-Ban",
        "category": ["sunglasses"],
        "gender": ["unisex"],
        "description": "The original pilot's choice since 1937. Iconic teardrop lenses and gold frame.",
        "face_shapes": ["oval", "heart"],
        "frame_shapes": ["aviator"],
        "frame_materials": ["metal"],
        "frame_colors": ["gold"],
        "lens_shapes": ["teardrop"],
        "lens_colors": ["gradient brown"],
        "arm_size_mm": [135, 137, 139, 140, 142, 145],
        "lens_size_mm": [55, 58, 62],
        "bridge_size_mm": [12, 13, 14, 15],
        "pd_mm": [63, 65, 67],
        "supports_power": True,
        "prescription_types": ["single_vision", "progressive"],
        "sph_min": -6.0, "sph_max": 5.0, "cyl_min": -2.5, "cyl_max": 2.5, "axis_min": 1, "axis_max": 180,
        "blue_cut": True, "anti_glare": True,
        "usage": ["travel"], "price_usd": 144.90, "power_price_usd": 150.00, "currency": "USD",
        "stock": 20, "rating": 4.9,
        "keywords": ["pilot"], "tone_descriptors": ["iconic"],
        "style_tags": ["timeless"], "recommended_for": ["pilots"],
        "occasion": ["driving"], "tags": ["classic-metal"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/luximages/0RB3025__001_51_030Afw350fh218.75.png"]
    },
    {
        "name": "Gucci Glamour Square",
        "brand": "Gucci",
        "category": ["sunglasses"],
        "gender": ["female"],
        "description": "Oversized square frame with a vintage flair and gold metal temples.",
        "face_shapes": ["round", "oval"],
        "frame_shapes": ["square"],
        "frame_materials": ["acetate", "metal"],
        "frame_colors": ["tortoise", "gold"],
        "lens_shapes": ["square"],
        "lens_colors": ["gradient brown"],
        "arm_size_mm": [140, 142, 144, 145],
        "lens_size_mm": [54, 55, 56, 57, 58],
        "bridge_size_mm": [18, 19, 20, 21, 22],
        "pd_mm": [61, 62, 63],
        "supports_power": True,
        "prescription_types": ["single_vision"],
        "sph_min": -4.0, "sph_max": 3.0, "cyl_min": -2.0, "cyl_max": 2.0, "axis_min": 1, "axis_max": 180,
        "blue_cut": False, "anti_glare": True,
        "usage": ["luxury"], "price_usd": 191.27, "power_price_usd": 210.00, "currency": "USD",
        "stock": 4, "rating": 4.9,
        "keywords": ["boutique"], "tone_descriptors": ["sophisticated"],
        "style_tags": ["70s-revival"], "recommended_for": ["stylists"],
        "occasion": ["shopping"], "tags": ["italy-made"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/product_images/Gucci-GG0632S-002-56-Sunglassesfw350fh218.75.jpg"]
    },
    {
        "name": "Ray-Ban Butterfly Chic",
        "brand": "Ray-Ban",
        "category": ["sunglasses"],
        "gender": ["female"],
        "description": "Features an oversized butterfly shape. Lightweight and elegant.",
        "face_shapes": ["square", "heart"],
        "frame_shapes": ["butterfly"],
        "frame_materials": ["propionate"],
        "frame_colors": ["tortoise"],
        "lens_shapes": ["rounded"],
        "lens_colors": ["gradient brown"],
        "arm_size_mm": [142, 143, 144, 145, 146, 147],
        "lens_size_mm": [52, 53, 54, 55, 56],
        "bridge_size_mm": [14, 15, 16, 17, 18],
        "pd_mm": [60, 61, 62],
        "supports_power": True,
        "prescription_types": ["single_vision"],
        "sph_min": -6.0, "sph_max": 4.0, "cyl_min": -2.5, "cyl_max": 2.5, "axis_min": 1, "axis_max": 180,
        "blue_cut": True, "anti_glare": True,
        "usage": ["daily"], "price_usd": 123.84, "power_price_usd": 135.00, "currency": "USD",
        "stock": 9, "rating": 4.6,
        "keywords": ["feminine"], "tone_descriptors": ["elegant"],
        "style_tags": ["modern"], "recommended_for": ["daily-wearers"],
        "occasion": ["brunch"], "tags": ["lightweight"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/luximages/0RB4378__710_13_030Afw350fh218.75.png"]
    },
    {
        "name": "Ray-Ban Aviator Arista",
        "brand": "Ray-Ban",
        "category": ["sunglasses"],
        "gender": ["unisex"],
        "description": "Polished gold Arista frame with heritage green lenses.",
        "face_shapes": ["oval", "square"],
        "frame_shapes": ["aviator"],
        "frame_materials": ["metal"],
        "frame_colors": ["gold"],
        "lens_shapes": ["teardrop"],
        "lens_colors": ["green"],
        "arm_size_mm": [135, 137, 139, 140, 142],
        "lens_size_mm": [58, 62],
        "bridge_size_mm": [13, 14, 15],
        "pd_mm": [64, 65, 66],
        "supports_power": True,
        "prescription_types": ["single_vision"],
        "sph_min": -7.0, "sph_max": 6.0, "cyl_min": -3.0, "cyl_max": 3.0, "axis_min": 1, "axis_max": 180,
        "blue_cut": False, "anti_glare": True,
        "usage": ["professional"], "price_usd": 134.85, "power_price_usd": 150.00, "currency": "USD",
        "stock": 12, "rating": 4.9,
        "keywords": ["gold"], "tone_descriptors": ["distinguished"],
        "style_tags": ["vintage"], "recommended_for": ["executives"],
        "occasion": ["weddings"], "tags": ["g15"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/luximages/0RB3025__181_030Afw350fh218.75.png"]
    },
    {
        "name": "Ray-Ban Justin Matte",
        "brand": "Ray-Ban",
        "category": ["sunglasses"],
        "gender": ["male"],
        "description": "Fresh rubberized finish frame with rectangle lenses.",
        "face_shapes": ["round", "oval"],
        "frame_shapes": ["rectangular"],
        "frame_materials": ["nylon"],
        "frame_colors": ["tortoise"],
        "lens_shapes": ["rectangular"],
        "lens_colors": ["gradient brown"],
        "arm_size_mm": [140, 142, 143, 145, 147],
        "lens_size_mm": [53, 54, 55, 56],
        "bridge_size_mm": [15, 16, 17, 18],
        "pd_mm": [64, 65, 66],
        "supports_power": True,
        "prescription_types": ["single_vision"],
        "sph_min": -8.0, "sph_max": 6.0, "cyl_min": -3.0, "cyl_max": 3.0, "axis_min": 1, "axis_max": 180,
        "blue_cut": True, "anti_glare": True,
        "usage": ["active"], "price_usd": 147.23, "power_price_usd": 145.00, "currency": "USD",
        "stock": 18, "rating": 4.7,
        "keywords": ["rubberized"], "tone_descriptors": ["edgy"],
        "style_tags": ["streetwear"], "recommended_for": ["youth"],
        "occasion": ["casual"], "tags": ["matte"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/luximages/0RB4165__865_T5_030Afw350fh218.75.png"]
    },
    {
        "name": "Ray-Ban Minimalist Gold",
        "brand": "Ray-Ban",
        "category": ["sunglasses"],
        "gender": ["unisex"],
        "description": "Refined metal frame with thin bridge and slender temples.",
        "face_shapes": ["all"],
        "frame_shapes": ["oval"],
        "frame_materials": ["metal"],
        "frame_colors": ["gold"],
        "lens_shapes": ["oval"],
        "lens_colors": ["brown"],
        "arm_size_mm": [142, 143, 144, 145, 146],
        "lens_size_mm": [53, 54, 55, 56],
        "bridge_size_mm": [17, 18, 19, 20],
        "pd_mm": [62, 63, 64],
        "supports_power": True,
        "prescription_types": ["single_vision"],
        "sph_min": -5.0, "sph_max": 4.0, "cyl_min": -2.0, "cyl_max": 2.0, "axis_min": 1, "axis_max": 180,
        "blue_cut": True, "anti_glare": True,
        "usage": ["professional"], "price_usd": 132.76, "power_price_usd": 150.00, "currency": "USD",
        "stock": 6, "rating": 4.6,
        "keywords": ["thin"], "tone_descriptors": ["clean"],
        "style_tags": ["minimalist"], "recommended_for": ["professionals"],
        "occasion": ["office"], "tags": ["slim"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/product_images/Ray-Ban-Sunglasses-RB3774D-001-73-Afw350fh218.75.png"]
    },
    {
        "name": "Ray-Ban Round Fleck",
        "brand": "Ray-Ban",
        "category": ["sunglasses"],
        "gender": ["unisex"],
        "description": "Iconic round shape with a flat bridge and tortoise finish.",
        "face_shapes": ["square", "heart"],
        "frame_shapes": ["round"],
        "frame_materials": ["propionate"],
        "frame_colors": ["tortoise"],
        "lens_shapes": ["round"],
        "lens_colors": ["brown"],
        "arm_size_mm": [143, 144, 145, 146, 147, 150],
        "lens_size_mm": [48, 49, 50, 51, 52],
        "bridge_size_mm": [19, 20, 21, 22],
        "pd_mm": [60, 62, 64],
        "supports_power": True,
        "prescription_types": ["progressive"],
        "sph_min": -10.0, "sph_max": 8.0, "cyl_min": -4.0, "cyl_max": 4.0, "axis_min": 1, "axis_max": 180,
        "blue_cut": True, "anti_glare": True,
        "usage": ["fashion"], "price_usd": 130.72, "power_price_usd": 155.00, "currency": "USD",
        "stock": 11, "rating": 4.8,
        "keywords": ["boho"], "tone_descriptors": ["trendy"],
        "style_tags": ["modern-retro"], "recommended_for": ["artists"],
        "occasion": ["festivals"], "tags": ["round"],
        "images": ["https://us.shadestation.com/media/thumbs/350x218.75/media/luximages/0RB2180__710_73_030Afw350fh218.75.png"]
    }
]

# -------------------------------
# Step 3: Insert function
# -------------------------------
def add_product():
    db: Session = SessionLocal()
    try:
        for pdata in products_data:
            # Check if embedding exists in schema; if not, SQLAlchemy handles it
            product = Product(**pdata)
            db.add(product)
        
        db.commit()
        print(f"✅ {len(products_data)} products inserted successfully!")

    except Exception as e:
        db.rollback()
        print("❌ Error inserting product:", e)

    finally:
        db.close()

# -------------------------------
# Step 4: Run
# -------------------------------
if __name__ == "__main__":
    add_product()